Repository aws/jsii-compiler, pull requests merged in 2024-08, with the labels that each got.

#1216 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1218 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1217 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1219 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1220 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1221 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1223 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1222 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1225 fix: outDir tsconfig is incorrectly rejected (backport #1224)
  src/tsconfig/rulesets/jsii-configured-options.ts
  test/tsconfig/tsconfig-validator.test.ts
Labels: auto-approve, backport

#1226 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1227 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1228 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1229 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1231 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1232 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1235 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1236 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1237 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1230 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1239 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1240 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1241 fix(tsconfig): omitting `declaration` in custom config does not fail tsconfig validation
  src/tsconfig/rulesets/incompatible-options.ts
  src/tsconfig/rulesets/strict.public.ts
  test/compiler.test.ts
  test/tsconfig/tsconfig-validator.test.ts
Labels: backport-to-maintenance/v5.3

#1242 fix(tsconfig): omitting `declaration` in custom config does not fail tsconfig validation (backport #1241)
  src/tsconfig/rulesets/incompatible-options.ts
  src/tsconfig/rulesets/strict.public.ts
  test/compiler.test.ts
  test/tsconfig/tsconfig-validator.test.ts
Labels: auto-approve, backport

#1238 fix: typesVersions not respecting outDir from tsconfig file
  src/assembler.ts
  src/compiler.ts
  src/downlevel-dts.ts
  src/helpers.ts
  test/downlevel.test.ts
Labels: backport-to-maintenance/v5.3

#1243 fix: typesVersions not respecting outDir from tsconfig file (backport #1238)
  src/assembler.ts
  src/compiler.ts
  src/downlevel-dts.ts
  src/helpers.ts
  test/downlevel.test.ts
Labels: auto-approve, backport

#1244 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1245 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1246 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1247 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1249 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1248 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1250 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1251 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1252 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1253 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1254 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1257 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1258 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1259 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1260 chore(deps): upgrade dependencies
  README.md
  yarn.lock
Labels: auto-approve

#1261 chore(deps): upgrade dependencies
  README.md
  yarn.lock
Labels: auto-approve

#1264 fix: error messages are getting lost (backport #1263)
  src/assembler.ts
  src/common/find-utils.ts
  src/compiler.ts
  src/helpers.ts
  src/main.ts
  src/project-info.ts
  src/transforms/deprecated-remover.js
  src/transforms/deprecated-remover.js.map
  src/transforms/deprecated-remover.ts
  src/transforms/deprecation-warnings.js
  src/transforms/deprecation-warnings.js.map
  src/transforms/runtime-info.js
  src/transforms/runtime-info.js.map
  src/transforms/utils.js
  src/transforms/utils.js.map
  src/utils.ts
Labels: auto-approve, backport

#1262 feat(tsconfig): mark verbatimModuleSyntax, isolatedModules & isolatedDeclarations options as configurable
  src/tsconfig/rulesets/configurable-options.ts
Labels: backport-to-maintenance/v5.3, backport-to-maintenance/v5.4

#1267 feat(tsconfig): mark verbatimModuleSyntax & isolatedModules options as configurable (backport #1262)
  src/tsconfig/rulesets/configurable-options.ts
Labels: auto-approve, backport

#1266 feat(tsconfig): mark verbatimModuleSyntax & isolatedModules options as configurable (backport #1262)
  src/tsconfig/rulesets/configurable-options.ts
Labels: auto-approve, backport

#1268 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1269 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1270 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1271 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1272 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1273 chore(deps): upgrade dependencies
  .gitattributes
  package.json
  yarn.lock
Labels: auto-approve

#1274 chore: config backport to support ts5.5 release (backport #1256)
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.4.yml
  .github/workflows/auto-tag-releases-v5.4.yml
  .github/workflows/upgrade-maintenance-v5.4.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/support.ts
  releases.json
Labels: auto-approve, backport

#1276 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1277 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1278 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1279 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1280 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1282 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1283 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1281 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1284 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1285 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1286 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1287 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1289 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1290 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1291 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1292 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1294 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1293 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
