Repository aws/jsii-compiler, pull requests merged in 2024-07, with the labels that each got.

#1144 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1145 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1147 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1148 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1149 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1150 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1151 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1152 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1153 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1154 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1155 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1158 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1159 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1160 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1162 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1163 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1165 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1166 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1167 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1168 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1170 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1171 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1172 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1173 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1174 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1175 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1176 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1177 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1178 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1179 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1180 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1181 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1186 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1187 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1188 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1189 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1190 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1191 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1192 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1193 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1194 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1195 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1196 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1197 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1198 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1199 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1200 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1202 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1203 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1204 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1206 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1207 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1208 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1209 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1210 chore: fix ci PRs might get merged with failing tests
  .github/workflows/build.yml
  projenrc/build-workflow.ts
Labels: backport-to-maintenance/v5.3

#1211 chore: fix ci PRs might get merged with failing tests (backport #1210)
  .github/workflows/build.yml
  projenrc/build-workflow.ts
Labels: auto-approve, backport

#1212 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1213 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1214 chore(deps): upgrade dependencies
  .github/workflows/backport.yml
  package.json
  yarn.lock
Labels: auto-approve

#1215 chore(deps): upgrade dependencies
  .github/workflows/backport.yml
  package.json
  yarn.lock
Labels: auto-approve
