Repository aws/jsii-compiler, pull requests merged in 2024-12, with the labels that each got.

#1528 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1529 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1530 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1531 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1532 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1534 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1535 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1536 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1537 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1538 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1539 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1540 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1541 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1542 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1543 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1544 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1545 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1546 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1547 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1548 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1549 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1550 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1551 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1552 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1553 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1554 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1555 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1556 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1557 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1558 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1559 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1560 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1561 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1562 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1563 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1564 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1565 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1566 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1567 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1568 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1569 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1570 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1571 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1572 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1573 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1574 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1576 fix: `lib` setting from custom config is ignored
  src/compiler.ts
  test/compiler.test.ts
Labels: backport-to-maintenance/v5.4, backport-to-maintenance/v5.5, backport-to-maintenance/v5.6

#1579 fix: `lib` setting from custom config is ignored (backport #1576)
  src/compiler.ts
  test/compiler.test.ts
Labels: auto-approve, backport

#1577 fix: `lib` setting from custom config is ignored (backport #1576)
  src/compiler.ts
  test/compiler.test.ts
Labels: auto-approve, backport

#1578 fix: `lib` setting from custom config is ignored (backport #1576)
  src/compiler.ts
  test/compiler.test.ts
Labels: auto-approve, backport

#1580 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1581 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1582 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1575 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1583 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1584 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1585 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1586 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1588 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1592 chore: `Match.arrEq` is not defined for arrays containing `undefined` (backport #1589)
  test/tsconfig/validator.test.ts
Labels: auto-approve, backport

#1590 chore: `Match.arrEq` is not defined for arrays containing `undefined` (backport #1589)
  test/tsconfig/validator.test.ts
Labels: auto-approve, backport

#1591 chore: `Match.arrEq` is not defined for arrays containing `undefined` (backport #1589)
  test/tsconfig/validator.test.ts
Labels: auto-approve, backport

#1593 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1595 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1596 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1594 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1597 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1599 fix: use maps instead of literals in `configureCategories` (backport #1598)
  src/jsii-diagnostic.ts
  test/jsii-diagnostic.test.ts
Labels: auto-approve, backport

#1600 fix: use maps instead of literals in `configureCategories` (backport #1598)
  src/jsii-diagnostic.ts
  test/jsii-diagnostic.test.ts
Labels: auto-approve, backport

#1602 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1603 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1604 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1605 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1606 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1607 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1608 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1609 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1610 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1611 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1612 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1613 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1614 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1587 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1615 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1616 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1617 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1618 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1619 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1620 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1621 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1622 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1623 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1624 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1625 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1627 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1628 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1629 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1630 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1631 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1632 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1633 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve
