Repository aws/jsii-compiler, pull requests merged in 2024-06, with the labels that each got.

#1034 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1035 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1036 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1037 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1039 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1038 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1040 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1041 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1042 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1043 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1045 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1044 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1047 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1048 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1049 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1050 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1051 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1052 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1053 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1054 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1055 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1061 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1063 chore: use latest node versions (backport #1060)
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .projenrc.ts
  projenrc/build-workflow.ts
  projenrc/common.ts
  projenrc/release.ts
Labels: auto-approve, backport

#1062 chore: use latest node versions (backport #1060)
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .projenrc.ts
  projenrc/build-workflow.ts
  projenrc/common.ts
  projenrc/release.ts
Labels: auto-approve, backport

#1065 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1066 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve

#1067 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1069 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1073 fix: cannot resolve project references (backport #1072)
  fixtures/@fixtures/jsii-composite/.gitignore
  fixtures/@fixtures/jsii-composite/.npmignore
  fixtures/@fixtures/jsii-composite/LICENSE
  fixtures/@fixtures/jsii-composite/NOTICE
  fixtures/@fixtures/jsii-composite/lib/index.ts
  fixtures/@fixtures/jsii-composite/package.json
  src/compiler.ts
  test/compiler.test.ts
Labels: auto-approve, backport

#1074 fix: cannot resolve project references (backport #1072)
  fixtures/@fixtures/jsii-composite/.gitignore
  fixtures/@fixtures/jsii-composite/.npmignore
  fixtures/@fixtures/jsii-composite/LICENSE
  fixtures/@fixtures/jsii-composite/NOTICE
  fixtures/@fixtures/jsii-composite/lib/index.ts
  fixtures/@fixtures/jsii-composite/package.json
  src/compiler.ts
  test/compiler.test.ts
Labels: auto-approve, backport

#1075 fix(docs): remove newlines on windows by replacing carriage return `\r\n` with spaces (backport #1058)
  src/docs.ts
Labels: auto-approve, backport

#1077 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1078 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1079 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1080 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1081 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1082 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1084 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1085 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1086 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1087 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1088 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1089 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1090 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1091 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1092 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1093 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1095 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1094 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1097 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1098 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1099 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1100 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1101 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1102 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1104 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1105 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1106 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1107 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1108 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1109 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1110 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1111 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1112 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1113 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1114 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1115 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1116 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1117 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1118 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1120 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1121 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1122 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1123 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1124 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1126 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1127 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1128 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1103 fix(docs): split paragraphs by both Unix and Windows newlines
  src/docs.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#1131 fix(docs): split paragraphs by both Unix and Windows newlines (backport #1103)
  src/docs.ts
Labels: auto-approve, backport

#1130 fix(docs): split paragraphs by both Unix and Windows newlines (backport #1103)
  src/docs.ts
Labels: auto-approve, backport

#1132 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1133 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1134 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1135 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1136 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1137 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1138 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1140 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1139 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1141 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve

#1142 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve

#1143 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve
