Repository aws/jsii-compiler, pull requests merged in 2024-10, with the labels that each got.

#1383 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1384 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1385 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1386 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1388 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1390 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1391 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1392 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1393 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1394 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1395 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1396 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1397 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1399 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1398 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1400 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1389 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1401 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1402 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1403 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1404 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1405 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1407 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1408 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1409 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1410 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1411 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1412 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1413 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1414 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1415 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1416 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1417 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1418 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1419 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev-v5.4.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases-v5.4.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve

#1420 chore(deps): upgrade dependencies
  .backportrc.json
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve

#1421 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev-v5.4.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases-v5.4.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/files.json
  yarn.lock
Labels: auto-approve

#1422 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1423 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1425 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1426 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1427 chore(deps): upgrade dependencies
  .github/workflows/pull-request-lint.yml
  package.json
  yarn.lock
Labels: auto-approve

#1428 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1429 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1430 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1424 chore(deps): upgrade dependencies
  .github/workflows/pull-request-lint.yml
  package.json
  yarn.lock
Labels: auto-approve

#1431 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1432 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1433 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1434 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1435 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1436 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1437 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1438 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1439 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1440 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1441 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1442 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1444 chore(deps): upgrade dependencies
  .github/workflows/pull-request-lint.yml
  package.json
  yarn.lock
Labels: auto-approve

#1445 chore(deps): upgrade dependencies
  .github/workflows/pull-request-lint.yml
  package.json
  yarn.lock
Labels: auto-approve

#1446 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1447 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1448 fix: omitting optional property fails C# compilation
  src/jsii-diagnostic.ts
  src/validator.ts
  test/__snapshots__/negatives.test.ts.snap
  test/negatives/neg.missing-abstract.ts
Labels: backport-to-maintenance/v5.3, backport-to-maintenance/v5.4

#1450 fix: omitting optional property fails C# compilation (backport #1448)
  src/jsii-diagnostic.ts
  src/validator.ts
  test/__snapshots__/negatives.test.ts.snap
  test/negatives/neg.missing-abstract.ts
Labels: auto-approve, backport

#1451 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1452 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
