Repository aws/jsii-compiler, pull requests merged in 2024-05, with the labels that each got.

#925 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#926 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#927 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#928 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#929 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#930 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#932 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#933 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#934 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#935 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#936 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#937 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#938 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#939 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#940 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#941 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#942 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#943 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#944 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#945 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#946 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#947 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#949 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#948 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#950 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#952 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#951 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#953 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#954 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#955 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#957 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#958 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#959 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#960 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#962 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#961 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#963 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#965 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#964 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#966 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#967 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#968 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#970 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#971 chore(deps): upgrade dependencies
  .projen/deps.json
  .projenrc.ts
  .vscode/settings.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#973 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#974 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#975 chore(deps): upgrade dependencies
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#977 chore: enable backports of PRs to previous version lines (backport #976)
  .backportrc.json
  .gitattributes
  .github/workflows/backport.yml
  .gitignore
  .npmignore
  .projen/files.json
  .projenrc.ts
  projenrc/support.ts
Labels: auto-approve, backport

#978 chore: enable backports of PRs to previous version lines (backport #976)
  .backportrc.json
  .gitattributes
  .github/workflows/backport.yml
  .gitignore
  .npmignore
  .projen/files.json
  .projenrc.ts
  projenrc/support.ts
Labels: auto-approve, backport

#980 feat: user-provided TypeScript config (backport #931)
  build-tools/code-gen.ts
  src/case.ts
  src/compiler.ts
  src/jsii-diagnostic.ts
  src/main.ts
  src/project-info.ts
  src/tsconfig/compiler-options.ts
  src/tsconfig/index.ts
  src/tsconfig/rulesets/configurable.ts
  src/tsconfig/rulesets/generated.public.ts
  src/tsconfig/rulesets/incompatible-options.ts
  src/tsconfig/rulesets/minimal.public.ts
  src/tsconfig/rulesets/strict.public.ts
  src/tsconfig/tsconfig-validator.ts
  src/tsconfig/validator.ts
  test/compiler.test.ts
  test/project-info.test.ts
  test/tsconfig/helpers.ts
  test/tsconfig/tsconfig-validator.test.ts
  test/tsconfig/validator.test.ts
  yarn.lock
Labels: auto-approve, backport

#981 fix: files are not excluded when using user-provided tsconfig (and various other fixes and improvements) (backport #969)
  src/compiler.ts
  src/jsii-diagnostic.ts
  src/main.ts
  src/project-info.ts
  src/tsconfig/rulesets/configurable-options.ts
  src/tsconfig/rulesets/configurable.ts
  src/tsconfig/rulesets/deprecated-options.ts
  src/tsconfig/rulesets/generated.public.ts
  src/tsconfig/rulesets/jsii-configured-options.ts
  src/tsconfig/rulesets/minimal.public.ts
  src/tsconfig/rulesets/strict-family-options.ts
  src/tsconfig/rulesets/strict.public.ts
  test/compiler.test.ts
  test/project-info.test.ts
Labels: auto-approve, backport

#982 fix: files are not excluded when using user-provided tsconfig (and various other fixes and improvements) (backport #969)
  src/compiler.ts
  src/jsii-diagnostic.ts
  src/main.ts
  src/project-info.ts
  src/tsconfig/rulesets/configurable-options.ts
  src/tsconfig/rulesets/configurable.ts
  src/tsconfig/rulesets/deprecated-options.ts
  src/tsconfig/rulesets/generated.public.ts
  src/tsconfig/rulesets/jsii-configured-options.ts
  src/tsconfig/rulesets/minimal.public.ts
  src/tsconfig/rulesets/strict-family-options.ts
  src/tsconfig/rulesets/strict.public.ts
  test/compiler.test.ts
  test/project-info.test.ts
Labels: auto-approve, backport

#983 chore: fix failing tsconfig validator prop test
  src/tsconfig/validator.ts
  test/tsconfig/validator.test.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#984 chore: fix failing tsconfig validator prop test (backport #983)
  src/tsconfig/validator.ts
  test/tsconfig/validator.test.ts
Labels: auto-approve, backport

#986 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#987 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#988 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#989 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#990 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#991 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#992 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#993 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#994 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#995 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#996 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#997 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#998 chore: restore ability to release maintenance version lines
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .projenrc.ts
  projenrc/release.ts
  projenrc/tag-release.ts
  projenrc/upgrade-dependencies.ts
Labels: backport-to-maintenance/v5.2, backport-to-maintenance/v5.3

#999 chore: restore ability to release maintenance version lines (backport #998)
  .backportrc.json
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/release.ts
  projenrc/support.ts
  projenrc/tag-release.ts
  projenrc/upgrade-dependencies.ts
  releases.json
  yarn.lock
Labels: auto-approve, backport

#1000 chore: restore ability to release maintenance version lines (backport #998)
  .backportrc.json
  .github/workflows/auto-tag-dev-v5.2.yml
  .github/workflows/auto-tag-dev-v5.3.yml
  .github/workflows/auto-tag-dev.yml
  .github/workflows/auto-tag-releases-v5.2.yml
  .github/workflows/auto-tag-releases-v5.3.yml
  .github/workflows/auto-tag-releases.yml
  .github/workflows/upgrade-maintenance-v5.2.yml
  .github/workflows/upgrade-maintenance-v5.3.yml
  .gitignore
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/release.ts
  projenrc/support.ts
  projenrc/tag-release.ts
  projenrc/upgrade-dependencies.ts
  releases.json
  yarn.lock
Labels: auto-approve, backport

#1001 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1002 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1003 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1004 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1005 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1006 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1007 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1009 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1008 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1010 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1011 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1012 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1013 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1015 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1016 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1017 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1018 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1019 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1021 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1020 chore(deps): upgrade dependencies
  .projen/tasks.json
  jest.config.json
  package.json
  yarn.lock
Labels: auto-approve

#1022 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1024 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1023 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1025 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1026 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1027 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1028 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1029 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1030 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1031 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1033 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1032 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve
